/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./es2018.macro.js#2a257f8c5cef6055c314c2fe5668662cee068d42
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _es2017$atrivialGramm;
let _initProto, _ObjectDecs;
import { spam as m } from '@bablr/boot';
import { CoveredBy, Node } from '@bablr/helpers/decorators';
import { o, eat, eatMatch } from '@bablr/helpers/grammar';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as Comment from '@bablr/language-en-c-comments';
import * as es2017 from './es2017.js';
export const dependencies = {
  Comment
};
export const defaultMatcher = m`.+: <_Expression />`;
export { powerLevels, reservedWords, assignmentOperators, assignmentOperatorAlternatives, unaryPrefixOperators, unaryPrefixOperatorAlternatives, unaryPostfixOperators, unaryPostfixOperatorAlternatives, getBinaryOperatorAlternatives } from './es2017.js';
export const canonicalURL = 'https://bablr.org/languages/universe/es6';
export const atrivialGrammar = class ES2018Grammar extends (_es2017$atrivialGramm = es2017.atrivialGrammar) {
  static {
    [_initProto] = _applyDecs(this, [[_ObjectDecs, 2, "Object"], [Node, 2, "ObjectPattern"], [Node, 2, "SpreadElement"]], [], 0, void 0, _es2017$atrivialGramm).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_ObjectDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], "Object")]() {
    yield eat(m`open: <*Punctuator '{' { balanced: '}' } />`);
    yield eat(m`properties[]$: <__List />`, o({
      element: m`<_ObjectMember />`,
      separator: m`#separatorTokens[]: <*Punctuator ',' />`,
      allowTrailingSeparator: true
    }));
    yield eat(m`close: <*Punctuator '}' { balancer: true } />`);
  }
  *ObjectMember() {
    if (yield eatMatch(m`<SpreadElement '...' />`)) {} else {
      yield eat(m`<Property />`);
    }
  }
  *ObjectPattern() {
    yield eat(m`openToken: <*Punctuator '{' { balanced: '}' } />`);
    yield eat(m`params[]+$: <__List />`, o({
      element: m`<PropertyPattern />`,
      allowTrailingSeparator: true,
      separator: m`#separatorTokens[]: <*Punctuator ',' />`
    }));
    if (yield eatMatch(m`params[]+$: <SpreadElement '...' />`)) {
      yield eatMatch(m`#separatorTokens[]: <*Punctuator ',' />`);
    }
    yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
  }
  *SpreadElement() {
    yield eat(m`sigilToken: <*Punctuator '...' />`);
    yield eat(m`value+$: <_Expression />`, o({
      power: 32
    }));
  }
};
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: :Comment: <__Trivia /[ \n\r\t]|\/\/|\/\*/ />`
}, atrivialGrammar);